### PR TITLE
added Telugu localization strings. (te)

### PR DESCRIPTION
**Pull request by srihariash999**
## Description

 Added Telugu (te) language localization strings.

## Type of Change

- [x] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Comment by srihariash999** [comment]
@googlebot I signed it!

**Comment by srihariash999** [comment]
@googlebot I consent.

**Comment by felangel** [comment]
@googlebot I consent.

**Review by felangel — APPROVED** [review]
Thanks so much for the contribution! 💙 🙏

**Comment by srihariash999** [comment]
@felangel Thank you for reviewing and accepting my changes. 💙🙌

**Pull request merged**
