### PR TITLE
Add Hungarian locale

### PR DESCRIPTION
**Pull request by siposbi**
## Description

With this PR siposbi and HLCaptain added Hungarian locale support.

## Type of Change

- [X] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Comment by siposbi** [comment]
@googlebot I signed it!

**Comment by HLCaptain** [comment]
@googlebot I signed it!

**Comment by HLCaptain** [comment]
@googlebot I consent.

**Comment by felangel** [comment]
@googlebot I consent.

**Review by felangel — APPROVED** [review]
Thanks so much for the contribution! 💙 🙏

**Pull request merged**
